name = "game-dev-bot"
main = "src/index.ts"
compatibility_date = "2024-09-23"

[triggers]
crons = ["0 0 * * *"]

[[d1_databases]]
binding       = "DB"
database_name = "game-dev-bot-db"
database_id   = "f8502f50-f8b7-414c-91a9-88f5ab7f7ee2"

[[kv_namespaces]]
binding = "KV"
id      = "73ac44186c7d481daa9761777af3c598"
